import {useEffect,useState} from 'react';
import {request} from '../../lib/client.mjs';
import DealerWorkspace from './DealerWorkspace';
import styles from './handoff.module.css';
const TOKEN=/^v1\.[a-f0-9-]{36}\.[A-Za-z0-9_-]{43}$/;
const failureText=code=>({HANDOFF_NOT_FOUND:'This handoff is not available at your signed-in location. Check the customer’s order and your shop location.',DEALER_SIGN_IN_REQUIRED:'Your dealer session has ended. Reload and sign in again.',DEALER_LOCATION_UNAVAILABLE:'This shop is not currently authorized to receive cards.',HANDOFF_CARD_COUNT_MISMATCH:'The confirmed cards do not match the paid order. Refresh and check every card again.',HANDOFF_ALREADY_ADVANCED:'These cards already have a later custody record. Open the location’s activity to review it.',REQUEST_CONFLICT:'This confirmation reference is already in use. Refresh the handoff before continuing.'})[code]||'The handoff could not be confirmed. Check its current status, then retry the same confirmation.';
export function DealerHandoffReview({data,csrf,onSignOut}){
 const [token,setToken]=useState(''),[handoff,setHandoff]=useState(null),[checked,setChecked]=useState([]),[count,setCount]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function read(value){if(!TOKEN.test(value)){setError('Open the customer’s handoff QR code with your phone camera.');return;}setBusy(true);setError('');try{const result=await request('/dealer/handoffs/read',{body:{token:value},csrf});setHandoff(result.handoff);}catch(failure){setError(failureText(failure.code));}finally{setBusy(false);}}
 useEffect(()=>{const value=window.location.hash.slice(1);setToken(value);read(value);},[csrf]);
 async function confirm(event){event.preventDefault();if(busy||!ready)return;setBusy(true);setError('');try{
  const key=`atlas-shop-receipt-v1:${handoff.id}`;let requestId=window.sessionStorage.getItem(key);if(!requestId){requestId=crypto.randomUUID();window.sessionStorage.setItem(key,requestId);}
  const result=await request('/dealer/handoffs/confirm',{body:{token,requestId,cardIds:[...checked].sort(),confirmedCount:Number(count)},csrf});setHandoff(result.handoff);
 }catch(failure){setError(failureText(failure.code));}finally{setBusy(false);}}
 const received=handoff?.status==='RECEIVED',ready=handoff&&!received&&checked.length===handoff.cardCount&&Number(count)===handoff.cardCount;
 return <main className={`account-main ${styles.workspace}`}><header className="section-heading"><div><span className="eyebrow">ATLAS · STAFF HANDOFF</span><h1>Receive the cards.</h1><p>Signed in at <strong>{data.location?.name}</strong></p></div><button className="secondary" onClick={onSignOut}>Sign out of shop</button></header>
 <section className={styles.panel}>{handoff?<><div className={styles.heading}><div><span className={styles.eyebrow}>PAYMENT CONFIRMED · {handoff.reference}</span><h2>{handoff.cardCount} {handoff.cardCount===1?'card':'cards'} for {handoff.location?.name}</h2></div><span className={styles.badge}>{received?'Received':'Awaiting your check'}</span></div>
 {received?<div className={styles.confirmed}><span aria-hidden="true">✓</span><div><h3>Shop receipt confirmed.</h3><p>{handoff.receipt.cardCount} {handoff.receipt.cardCount===1?'card':'cards'} · {new Date(handoff.receipt.receivedAt).toLocaleString()}</p><p>The customer can now see this receipt in their ATLAS account. ATLAS collection is a separate recorded step.</p><small>Receipt {handoff.receipt.id}</small></div></div>:<form onSubmit={confirm}><p>Match each card in front of you to the paid order. Confirm only after you have received all of them.</p><div className={styles.cards}>{handoff.cards.map((card,index)=><label key={card.cardId} className={styles.card}><input type="checkbox" checked={checked.includes(card.cardId)} disabled={busy} onChange={event=>setChecked(ids=>event.target.checked?[...ids,card.cardId]:ids.filter(id=>id!==card.cardId))}/><span><small>Card {index+1}</small><strong>{card.identity?.title||'Card identity unavailable'}</strong>{card.identity?.category&&<small>{card.identity.category}</small>}<small>Card ID · {card.cardId.slice(-8)}</small></span></label>)}</div>
 <label className={styles.count}>How many cards are in your hands?<input inputMode="numeric" pattern="[0-9]*" value={count} onChange={event=>setCount(event.target.value)} disabled={busy} placeholder="Enter the full count" aria-describedby="receipt-count-note"/></label><p id="receipt-count-note" className={styles.note}>All {handoff.cardCount} cards must be present. If a card is missing or incorrect, keep this handoff open and resolve it with the customer before confirming.</p>
 <button className="primary" type="submit" disabled={!ready||busy}>{busy?'Confirming receipt…':`Confirm receipt of ${handoff.cardCount} ${handoff.cardCount===1?'card':'cards'}`}</button></form>}
 <button className="secondary" disabled={busy} onClick={()=>read(token)}>Refresh handoff status</button></>:!error&&<p role="status">Opening the paid order…</p>}{error&&<p role="alert">{error}</p>}
 </section><a className="text-link" href="/account/dealer">View shop activity ↗</a></main>;
}
export default function DealerHandoff({unavailable=false}){return <DealerWorkspace unavailable={unavailable} handoff renderAuthorized={props=><DealerHandoffReview {...props}/>}/>;}
