import {object,requireThat,digest,canonical} from '@atlas/manual-service/contract';
import {variantBinding,variantRefreshable} from './variant-job-store.mjs';
export function variantReviewStatus({card,job,confirmation,approvalReady,reason,legacyApproved=false}){
 const selected=confirmation?{actionId:confirmation.action_id,decision:confirmation.decision,candidateId:confirmation.candidate_id,selectedCandidateId:confirmation.candidate_id,sourceHash:confirmation.source_hash,identityRevision:confirmation.identity_revision,identityHash:confirmation.identity_hash,resultHash:confirmation.result_hash,catalogManifestHash:confirmation.catalog_hash,recheckState:confirmation.recheck_state,recheckRetryable:confirmation.recheck_retryable===true,recheckReason:confirmation.recheck_reason??null,recheckAnalysisId:confirmation.recheck_analysis_id??null,reprocessRequired:confirmation.reprocess_required,analysisActionId:confirmation.analysis_action_id,observedFeatures:confirmation.observed_features}:null;
 return {enabled:true,legacyApproved,...variantBinding(card),revision:card.revision,state:job?['RUNNING','REQUESTED'].includes(job.state)?'SEARCHING':job.state:'NOT_REQUESTED',jobId:job?.key??null,refreshable:variantRefreshable(job),refreshRequestId:job?.input?.generation??null,resultHash:job?.result_hash??null,catalogManifestHash:job?.catalog_hash??null,result:job?.result??null,confirmation:selected,approvalReady,reason};
}
const acknowledgement=(operation,input)=>({operation,requestId:operation==='CONFIRM'?input.actionId:input.requestId,sourceHash:input.sourceHash,identityRevision:input.identityRevision,identityHash:input.identityHash});
export function createVariantReviewService({store,workflow,readReferenceImage=null}){return Object.freeze({enabled:true,
 status:async(staff,cardId)=>variantReviewStatus(await store.read(staff,cardId)),
 async image(staff,cardId,sha256){requireThat(/^[a-f0-9]{64}$/.test(sha256)&&typeof readReferenceImage==='function',404,'VARIANT_IMAGE_NOT_FOUND');const saved=await store.read(staff,cardId);const snapshot=saved.job?.result?.catalog,candidate=snapshot?.candidates.find(c=>c.images.some(i=>i.sha256===sha256)),image=candidate?.images.find(i=>i.sha256===sha256);requireThat(image&&(image.publication||candidate.authority==='provider_candidate'&&image.provenance?.usage==='provider_reference'),404,'VARIANT_IMAGE_NOT_FOUND');const result=await readReferenceImage({snapshot,candidateId:candidate.candidateId,imageId:image.imageId},{signal:AbortSignal.timeout(15000)});requireThat(result?.bytes&&result.bytes.length<=4*1024*1024&&digest(result.bytes)===sha256&&result.mimeType===image.mimeType,503,'VARIANT_IMAGE_UNVERIFIED');const current=await store.read(staff,cardId);requireThat(canonical(variantBinding(current.card))===canonical(variantBinding(saved.card))&&current.job?.key===saved.job?.key&&current.job?.result_hash===saved.job?.result_hash,409,'VARIANT_RESULT_STALE');return {bytes:result.bytes,contentType:result.mimeType};},
 async refresh(staff,cardId,input){await store.refresh(staff,cardId,input);return {...variantReviewStatus(await store.read(staff,cardId)),acknowledgedRequest:acknowledgement('REFRESH',input)};},
 resolve:async({staff,card,action})=>(await store.resolve(staff,card,action)).identity,
 async confirm(staff,cardId,input){object(input,['actionId','expectedRevision','sourceHash','identityRevision','identityHash','jobId','resultHash','decision','candidateId','reviewed',...(input.decision==='MANUAL'?['manualParallel','observedFeatures']:[]),...(Object.hasOwn(input,'referencePermission')?['referencePermission']:[])]);
  const {actionId,expectedRevision,...fields}=input;await workflow.service.execute(staff,cardId,{actionId,expectedRevision,action:{type:'VARIANT_CONFIRM',...fields}});
  return {...variantReviewStatus(await store.read(staff,cardId)),acknowledgedRequest:acknowledgement('CONFIRM',input)};},
});}
