import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import type { WorkflowCommandV2, WorkflowEventV2 } from '@tenkings/database';
import { buildAdminHeaders } from '../../lib/adminHeaders';
import { buildWorkflowCommand, emptyWorkflowDraft, workflowActionLabels, workflowReceiptMatches, workflowMoney, type WorkflowDraft, type WorkflowAction, type WorkflowView } from '../../lib/inventoryWorkflow';
const inputClass = 'mt-2 w-full rounded-lg border border-white/20 bg-black/40 px-3 py-2.5 text-sm text-white focus:border-amber-300 focus:outline-none';
const buttonClass = 'rounded-lg border border-white/20 px-4 py-2 text-sm hover:border-amber-300 disabled:opacity-40';
const panelClass = 'rounded-2xl border border-white/15 bg-white/[0.025] p-5';
const money = workflowMoney;
function Field({ label, help, children }: { label: string; help?: string; children: ReactNode }) { return <label className="block text-sm text-white/85">{label}{children}{help && <span className="mt-1 block text-xs leading-5 text-white/55">{help}</span>}</label>; }
type Pending = { adminId: string; command: WorkflowCommandV2 };
type Receipt = { outcome: 'PREVIEW' | 'RECORDED' | 'REPLAY'; request_id: string; event: WorkflowEventV2; impact: { units: number; lots: number; batches: number; backdated: boolean } | null };
export default function InventoryWorkflowWorkspace({ token, adminId }: { token: string; adminId: string }) {
  const [view, setView] = useState<WorkflowView | null>(null), [draft, setDraft] = useState(emptyWorkflowDraft), [selected, setSelected] = useState<string[]>([]), [unitPage, setUnitPage] = useState(0);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [storageError, setStorageError] = useState(''), [pending, setPending] = useState<Pending | null>(null), [rejected, setRejected] = useState(false), [preview, setPreview] = useState<Receipt | null>(null);
  const uncertain = useRef(false), readAttempt = useRef(0), readController = useRef<AbortController | null>(null);
  const sessionRef = useRef({ token, adminId, generation: 0 });
  if (sessionRef.current.token !== token || sessionRef.current.adminId !== adminId) sessionRef.current = { token, adminId, generation: sessionRef.current.generation + 1 };
  const requestId = useRef(''), lock = useRef(false), pendingRef = useRef<Pending | null>(null), alive = useRef(true), controller = useRef<AbortController | null>(null);
  const storageKey = `ten-kings:inventory-workflow:pending:${adminId}`;
  const [query, setQuery] = useState('');
  const stopRequests = useCallback(() => { readAttempt.current++; readController.current?.abort(); controller.current?.abort(); }, []);
  const load = useCallback(async (queryString = '') => {
    const generation = sessionRef.current.generation, attempt = ++readAttempt.current;
    readController.current?.abort();
    const abort = new AbortController(), timer = setTimeout(() => abort.abort(), 30000); readController.current = abort;
    const current = () => alive.current && attempt === readAttempt.current && generation === sessionRef.current.generation && token === sessionRef.current.token && adminId === sessionRef.current.adminId;
    try {
      const response = await fetch('/api/v2/admin/inventory/workflow' + (queryString ? '?' + queryString : ''), { headers: buildAdminHeaders(token), cache: 'no-store', signal: abort.signal });
      if (!current()) return false;
      if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? 'An authorized admin session is required.' : 'Recorded workflow evidence is unavailable. The source schema and compatible app must be installed before receiving stock.');
      const next = await response.json() as WorkflowView;
      if (!current()) return false;
      if (next.version !== 2 || !Array.isArray(next.lots) || !Array.isArray(next.units) || !Array.isArray(next.events) || !Array.isArray(next.locations)) throw new Error('Workflow response could not be verified.');
      setView(next); setQuery(queryString); setSelected([]); setUnitPage(0); return true;
    } finally { clearTimeout(timer); }
  }, [token, adminId]);
  useEffect(() => {
    alive.current = true; const generation = sessionRef.current.generation;
    pendingRef.current = null; uncertain.current = false; requestId.current = ''; lock.current = false;
    setPending(null); setPreview(null); setView(null); setDraft(emptyWorkflowDraft()); setSelected([]); setQuery(''); setMessage(''); setStorageError(''); setRejected(false); setBusy(false);
    try {
      const saved = sessionStorage.getItem(storageKey);
      if (saved) { const value = JSON.parse(saved) as Pending; if (value.adminId !== adminId || !value.command?.request_id || !(value.command.event_kind in workflowActionLabels)) throw new Error('Invalid retry'); pendingRef.current = value; uncertain.current = true; setPending(value); setMessage('A saved submission is unresolved. Retry the exact saved evidence to recover its result.'); }
    } catch { setStorageError('Saved retry evidence could not be verified. It has been preserved; resolve it before submitting another event.'); }
    load().catch(error => { if (alive.current && generation === sessionRef.current.generation) setMessage(error.message); });
    return () => { alive.current = false; stopRequests(); };
  }, [adminId, load, storageKey, stopRequests]);
  const change = <K extends keyof WorkflowDraft>(key: K, value: WorkflowDraft[K]) => { setDraft(d => ({ ...d, [key]: value })); setPreview(null); };
  function choose(action: WorkflowAction | '') {
    const units = view?.units.filter(u => selected.includes(u.unit_id)) ?? [], same = (key: 'product_id') => units.length && units.every(u => u[key] === units[0][key]) ? units[0][key] ?? '' : '';
    const next = emptyWorkflowDraft(); next.action = action; next.lot = action === 'purchase_received' || action === 'opening_stock_recorded' ? '' : view?.selected_lot_id ?? ''; next.product = same('product_id');
    if (units.length && units.every(u => u.custody.custody_id === units[0].custody.custody_id)) next.fromCustody = units[0].custody.custody_id;
    if (view?.selected_batch) { const batch = view.selected_batch; next.batch = action === 'batch_loaded' ? '' : batch.data.batch_id; next.machine = batch.data.scope.machine_id; next.product = batch.data.scope.product_id; next.door = batch.data.scope.door_id ?? ''; next.location = batch.data.to.location_id ?? ''; }
    setDraft(next); requestId.current = ''; setPreview(null); setMessage('');
  }
  async function send(mode: 'preview' | 'record', exact?: Pending) {
    if ((!view && !exact) || lock.current || storageError) return;
    const generation = sessionRef.current.generation;
    const current = () => alive.current && generation === sessionRef.current.generation && token === sessionRef.current.token && adminId === sessionRef.current.adminId;
    lock.current = true; setBusy(true); setRejected(false); setMessage('');
    let timer: ReturnType<typeof setTimeout> | undefined; let definiteRejection = false;
    try {
      if (exact && exact.adminId !== adminId) throw new Error('This saved submission belongs to another admin session and cannot be retried.');
      if (!exact && pendingRef.current) throw new Error('Resolve the exact saved submission before starting another event.');
      if (!requestId.current) requestId.current = crypto.randomUUID();
      const command = exact?.command ?? buildWorkflowCommand(draft, requestId.current, selected, view!);
      if (mode === 'record') { const saved = exact ?? { adminId, command }; sessionStorage.setItem(storageKey, JSON.stringify(saved)); pendingRef.current = saved; setPending(saved); }
      const abort = new AbortController(); controller.current = abort; timer = setTimeout(() => abort.abort(), 35000);
      const response = await fetch('/api/v2/admin/inventory/workflow', { method: 'POST', headers: { ...buildAdminHeaders(token), 'Content-Type': 'application/json' }, cache: 'no-store', signal: abort.signal, body: JSON.stringify({ mode, command }) });
      const result = await response.json() as Receipt & { message?: string };
      if (!current()) return;
      if (!response.ok) { if ((response.status === 400 || response.status === 409) && !uncertain.current) { setRejected(true); definiteRejection = true; } throw new Error(result.message ?? 'The request was not accepted. Retry the same saved evidence after the source is available.'); }
      if (result.request_id !== command.request_id || !['PREVIEW', 'RECORDED', 'REPLAY'].includes(result.outcome) || mode === 'record' && result.outcome === 'PREVIEW' || !await workflowReceiptMatches(command, result.event, adminId)) throw new Error('Acceptance could not be verified. Keep the saved submission and retry its exact evidence.');
      if (!current()) return;
      setPreview(result);
      if (result.outcome === 'PREVIEW') { setMessage('Preview passed causal replay. Review the recorded facts below; saving appends the event.'); return; }
      try { sessionStorage.removeItem(storageKey); } catch { setStorageError('The event was accepted, but its exact retry record could not be cleared. Preserve it for recovery.'); }
      pendingRef.current = null; uncertain.current = false; setPending(null); requestId.current = ''; setDraft(emptyWorkflowDraft());
      setMessage(`${result.outcome === 'REPLAY' ? 'Recovered accepted' : 'Saved'} ${workflowActionLabels[command.event_kind].toLowerCase()}. Evidence ${result.event.source_event_id}`);
      await load(query);
    } catch (error) { if (!current()) return; if (mode === 'record' && pendingRef.current && !definiteRejection) uncertain.current = true; if (alive.current) setMessage((error instanceof Error ? error.message : 'Workflow request failed.') + (mode === 'record' && pendingRef.current ? ' The exact submission is saved for retry.' : '')); }
    finally { if (timer) clearTimeout(timer); if (current()) { lock.current = false; setBusy(false); } }
  }
  function discardRejected() { try { sessionStorage.removeItem(storageKey); pendingRef.current = null; uncertain.current = false; setPending(null); setRejected(false); requestId.current = ''; } catch { setStorageError('The rejected retry record could not be cleared.'); } }
  async function navigate(next: string) { if (lock.current || pendingRef.current) return; const generation = sessionRef.current.generation; lock.current = true; setBusy(true); try { if (await load(next)) { setDraft(emptyWorkflowDraft()); setPreview(null); } } catch (error) { if (alive.current && generation === sessionRef.current.generation) setMessage(error instanceof Error ? error.message : 'Evidence loading failed.'); } finally { if (alive.current && generation === sessionRef.current.generation) { lock.current = false; setBusy(false); } } }
  const field = (key: keyof WorkflowDraft, label: string, help?: string, textarea = false) => <Field label={label} help={help}>{textarea ? <textarea className={inputClass} rows={4} value={String(draft[key])} onChange={e => change(key, e.target.value as never)} /> : <input className={inputClass} value={String(draft[key])} onChange={e => change(key, e.target.value as never)} />}</Field>;
  const check = (key: keyof WorkflowDraft, label: string) => <label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={Boolean(draft[key])} onChange={e => change(key, e.target.checked as never)} />{label}</label>;
  const locationField = <Field label="Existing Location" help="Select the real site. Its Location ID does not identify a machine."><select className={inputClass} value={draft.location} onChange={e => change('location', e.target.value)}><option value="">Unset / transit has no Location</option>{view?.locations.map(l => <option key={l.id} value={l.id}>{l.name} — {l.slug}</option>)}</select></Field>;
  const scopeFields = <>{field('machine', 'Exact machine ID')}{field('product', 'Exact product ID')}{field('door', 'Door / slot ID', 'Leave unset only when evidence covers the whole machine product and does not identify a door.')}</>;
  const action = draft.action;
  const selectedLot = view?.lots.find(l => l.lot_id === view.selected_lot_id);
  return <div className="space-y-5">
    <div className={panelClass}><h2 className="text-xl font-semibold">Purchased stock and loading batches</h2><p className="mt-2 text-sm leading-6 text-white/65">Receive actual purchases at HQ, choose cost assignments, process and pack, then record physical loading and sales evidence. Grading and exact-vend identification are independent.</p><p className="mt-2 text-sm text-amber-100">{view?.notice ?? 'No stock or costs are assumed before recorded evidence is available.'}</p></div>
    {(message || storageError) && <div role="status" className="rounded-xl border border-amber-300/30 bg-amber-400/5 p-4 text-sm text-amber-100 break-words">{storageError || message}</div>}
    {pending && <div className={panelClass}><p className="text-sm">Unresolved submission: {workflowActionLabels[pending.command.event_kind]}. Its command and identity are preserved.</p><button type="button" className={buttonClass + ' mt-3'} disabled={busy || !!storageError} onClick={() => send('record', pending)}>Retry exact saved submission</button>{rejected && <button type="button" className={buttonClass + ' ml-3'} disabled={busy} onClick={discardRejected}>Edit rejected evidence</button>}</div>}
    {view && <>
      <fieldset disabled={busy || !!pending || !!storageError} className={panelClass + ' grid gap-4 md:grid-cols-2'}><Field label="Recorded purchase"><select className={inputClass} value={view.selected_lot_id ?? ''} onChange={e => navigate('lot_id=' + encodeURIComponent(e.target.value))}><option value="">Select a received lot</option>{view.lots.map(l => <option key={l.lot_id} value={l.lot_id}>{l.lot_id} — {l.quantity} cards · {money(l.total_cost_cents)}</option>)}</select></Field><Field label="Recorded loading batch"><select className={inputClass} value={view.selected_batch?.data.batch_id ?? ''} onChange={e => navigate(e.target.value ? 'batch_id=' + encodeURIComponent(e.target.value) : '')}><option value="">Select a loading batch / view purchase</option>{view.batches.map(b => <option key={b.batch_id} value={b.batch_id}>{b.batch_id} — {b.scope.machine_id} · {b.scope.product_id} · {b.scope.door_id ?? 'door unset'}</option>)}</select></Field>
        <div className="flex gap-2 text-xs"><button type="button" className={buttonClass} disabled={view.lot_offset === 0} onClick={() => navigate('lot_offset=' + Math.max(0, view.lot_offset - 100))}>Previous purchases</button><button type="button" className={buttonClass} disabled={view.lot_offset + view.lots.length >= view.lots_total} onClick={() => navigate('lot_offset=' + (view.lot_offset + 100))}>More purchases</button></div><div className="flex gap-2 text-xs"><button type="button" className={buttonClass} disabled={view.batch_offset === 0} onClick={() => navigate('batch_offset=' + Math.max(0, view.batch_offset - 100))}>Previous batches</button><button type="button" className={buttonClass} disabled={view.batch_offset + view.batches.length >= view.batches_total} onClick={() => navigate('batch_offset=' + (view.batch_offset + 100))}>More batches</button></div>
      </fieldset>
      {selectedLot && <div className={panelClass + ' text-sm'}><strong>{selectedLot.lot_id}</strong>{selectedLot.cancelled_event_id ? <><p className="mt-2 text-amber-100">Cancelled receipt entry · no available holdings. Original quantity: {selectedLot.quantity}.</p><p className="mt-1 break-words text-white/60">{selectedLot.cancellation_reason}</p><p className="mt-1 break-all text-white/50">{selectedLot.cancelled_event_id}</p></> : <><p className="mt-2">Documented purchase total: {money(selectedLot.total_cost_cents)} · {selectedLot.quantity} received cards.</p><p className="mt-1 break-words text-white/60">{selectedLot.unknown_reason ?? selectedLot.purchase_evidence_ref}</p><p className="mt-1 text-white/60">Allocation is {selectedLot.assignment_event_id ? 'recorded; individual basis is shown below.' : 'unset. No unit cost is inferred from the lot total.'}</p></>}</div>}
      <div className={panelClass}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Receipt roster · {view.units.length} identities</h3><div className="flex gap-2"><button type="button" className={buttonClass} disabled={busy || !!pending} onClick={() => setSelected(view.units.map(u => u.unit_id))}>Select entire roster</button><button type="button" className={buttonClass} disabled={busy || !!pending} onClick={() => setSelected([])}>Clear selection</button><button type="button" className={buttonClass} onClick={() => { const blob = new Blob([view.units.map(u => `${u.unit_id}\t${u.cost?.cost_cents === null || u.cost?.cost_cents === undefined ? '' : workflowMoney(u.cost.cost_cents).slice(1)}\t${u.cost?.evidence_ref ?? ''}`).join('\n')], { type: 'text/tab-separated-values' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'received-unit-roster.tsv'; anchor.click(); URL.revokeObjectURL(url); }}>Download roster</button></div></div><p className="mt-2 text-xs text-white/55">{selected.length} selected. Roster membership is not proof that a loaded unit remains unsold.</p>
        <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-white/50"><tr><th>Select</th><th>Unit / pack</th><th>Processing / custody</th><th>Acquisition basis</th><th>Asking price</th></tr></thead><tbody>{view.units.slice(unitPage * 100, (unitPage + 1) * 100).map(u => <tr key={u.unit_id} className="border-t border-white/10"><td className="py-3"><input aria-label={'Select ' + u.unit_id} type="checkbox" disabled={busy || !!pending} checked={selected.includes(u.unit_id)} onChange={e => setSelected(ids => e.target.checked ? [...ids, u.unit_id] : ids.filter(id => id !== u.unit_id))} /></td><td className="max-w-xs break-all pr-3">{u.unit_id}<div className="text-white/50">{u.pack_id ?? 'Unpacked'}</div></td><td className="pr-3">{u.stage}<div>{u.custody.custody_id}</div>{u.batch_id && <div className="text-amber-100">Batch membership · current unit identity uncertain</div>}{u.reservation && <div className="text-white/55">Reserved: {u.reservation.custody_id}</div>}</td><td className="pr-3">{money(u.cost?.cost_cents)}<div className="text-white/55">{u.cost?.basis.replaceAll('_', ' ') ?? 'Cost assignment unset'}</div><div className="max-w-xs break-words text-white/50">{u.cost?.unknown_reason ?? u.cost?.evidence_ref}</div></td><td>{money(u.intended_sale_price_cents)}</td></tr>)}</tbody></table></div><div className="mt-3 flex gap-3"><button type="button" className={buttonClass} disabled={unitPage === 0} onClick={() => setUnitPage(p => p - 1)}>Previous units</button><button type="button" className={buttonClass} disabled={(unitPage + 1) * 100 >= view.units.length} onClick={() => setUnitPage(p => p + 1)}>More units</button></div>
      </div>
      <form className={panelClass} onSubmit={e => { e.preventDefault(); send('record'); }}><fieldset disabled={busy || !!pending || !!storageError} className="space-y-5"><Field label="Record an actual workflow step"><select className={inputClass} value={action} onChange={e => choose(e.target.value as WorkflowAction | '')}><option value="">Choose the completed action</option>{Object.entries(workflowActionLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>
      {action && <><div className="grid gap-4 md:grid-cols-2">{field('at', 'Event time (UTC)', 'Historical entry uses the actual event time. Recorded time and operator are assigned by the server.')}<div className="self-end"><button type="button" className={buttonClass} onClick={() => change('at', new Date().toISOString())}>Use current time</button></div>{field('evidence', 'Event evidence reference', 'Reference the actual receipt, packing log, delivery note, count or sales record.')}
      {(action === 'purchase_received' || action === 'opening_stock_recorded') && <>{field('lot', 'New purchase lot ID')}{field('cycle', 'Acquisition cycle ID')}{field('quantity', 'Received card quantity')}{field('total', 'Documented purchase total (USD)', 'Blank means unknown; documented zero remains zero.')}{field('unknown', 'Reason purchase cost is unknown')}{field('purchaseEvidence', 'Purchase / invoice evidence')}{field('custody', action === 'opening_stock_recorded' ? 'Observed opening custody identity' : 'HQ custody identity', action === 'opening_stock_recorded' ? 'Use the evidenced location or machine custody at the historical count date.' : 'Use the actual hq: identity; new purchases enter as unprocessed stock.')}{locationField}{check('generateRoster', 'Create one permanent bookkeeping roster ID for each actual received card. These IDs do not create graded cards.')}</>}
      {action === 'opening_stock_recorded' && <><Field label="Observed opening processing state"><select className={inputClass} value={draft.stage} onChange={e => change('stage', e.target.value)}><option value="">Choose the evidenced state</option><option value="unprocessed">Unprocessed</option><option value="processing">Processing</option><option value="processed">Processed</option><option value="packed">Packed</option></select></Field>{scopeFields}{field('batch', 'Opening machine batch identity')}{field('packPrefix', 'Opening physical pack roster identity')}<p className="text-sm text-amber-100">This establishes stock at the evidenced count date. It does not invent a prior HQ receipt, zero prior stock, earlier load or sale. Machine scope must have no previously accepted history.</p></>}
      {action === 'purchase_cancelled' && <><p className="text-sm text-amber-100">{selectedLot ? `Selected receipt: ${selectedLot.lot_id} · ${selectedLot.quantity} original cards.` : 'Select the original recorded purchase first.'} {selectedLot?.cancellation_block_reason ?? 'Only an erroneous unused receipt can be cancelled. Its history and IDs remain permanent; a replacement is a separate receipt with new IDs.'}</p>{field('cancellationReason', 'Receipt cancellation reason', 'Describe the quantity, lot or roster entry error and cite its evidence.')}{check('confirmCancellation', 'This is an erroneous unused receipt entry. Cancel its available holdings and preserve its original evidence and identities.')}</>}
      {action === 'purchase_cost_documented' && <>{field('lot', 'Recorded lot ID')}{field('total', 'Correct documented purchase total (USD)')}{field('unknown', 'Reason purchase cost is unknown')}{field('purchaseEvidence', 'New purchase / correction evidence')}<p className="text-sm text-amber-100">The original receipt stays intact. Current unit costs become unset until a fresh assignment cites this corrected total.</p></>}
      {action === 'cost_assigned' && <>{field('lot', 'Recorded lot ID')}<Field label="Explicit acquisition cost method"><select className={inputClass} value={draft.method} onChange={e => change('method', e.target.value)}><option value="">Choose a cost method</option><option value="unassigned">Leave per-card cost unassigned</option><option value="documented_unit">Individually documented card prices</option><option value="equal_card">Explicit equal-card allocation</option><option value="explicit_per_card">Explicit unequal per-card allocation</option></select></Field>{field('unknown', 'Reason per-card cost is unassigned')}{field('assignmentEvidence', 'Allocation choice evidence')}{field('costs', 'Per-card costs', 'Paste the complete roster as tab-separated unit ID and USD amount. Documented individual costs also require a third evidence-reference column. Download the roster above; preserve its exact IDs.', true)}<p className="text-sm text-amber-100">Known assignments cover every card in the purchase and conserve the full total, including residual cents. A replacement assignment explicitly supersedes the current one.</p></>}
      {action === 'processed' && <><Field label="Processing state"><select className={inputClass} value={draft.stage} onChange={e => change('stage', e.target.value)}><option value="">Choose observed state</option><option value="processing">Processing started</option><option value="processed">Processing completed</option></select></Field>{field('product', 'Exact product ID')}{field('links', 'Optional real permanent-card links', 'One tab-separated receipt unit ID and existing permanent V2 card ID per line. Leave blank for ungraded stock. Grading is never invented.', true)}</>}
      {action === 'stock_corrected' && <>
        <p className="text-sm text-amber-100 md:col-span-2">Correct the current state of the selected identified stock. The original events, receipt identities and acquisition costs remain recorded. Enter the actual effective time of the correction; earlier reports retain the original history.</p>
        <Field label="Physical fact to correct"><select className={inputClass} value={draft.correctionKind} onChange={e => change('correctionKind', e.target.value)}><option value="">Choose the correction</option><option value="processing">Processing stage / product</option><option value="packing">Pack membership / unpack</option><option value="custody">Current custody</option></select></Field>
        {field('correctionReason', 'Holding correction reason', 'Describe the entry error or newly verified physical fact and its supporting evidence.')}
        {draft.correctionKind === 'processing' && <><Field label="Correct processing state"><select className={inputClass} value={draft.stage} onChange={e => change('stage', e.target.value)}><option value="">Choose the observed state</option><option value="unprocessed">Unprocessed</option><option value="processing">Processing</option><option value="processed">Processed</option><option value="packed">Packed — preserve current pack</option></select></Field>{draft.stage !== 'unprocessed' && field('product', 'Correct product ID')}<p className="text-sm text-white/65">Choose Packed to correct the product while keeping its current pack. Entering or leaving packed state uses Pack membership / unpack. A real permanent-card link stays attached.</p></>}
        {draft.correctionKind === 'packing' && <>{check('unpack', 'The selected held units are unpacked; preserve their old pack identities in history.')}{!draft.unpack && field('packPrefix', 'Correct physical pack roster identity', 'Record one actual pack per selected unit. Retired pack IDs cannot be reused.')}</>}
        {draft.correctionKind === 'custody' && <>{field('custody', 'Correct current custody', 'Use the actual hq: or transit: identity. Machine delivery requires a loading batch.')}{locationField}</>}
        <div className="md:col-span-2 space-y-2 text-xs text-white/65">{view.units.filter(u => selected.includes(u.unit_id)).map(u => <p key={u.unit_id} className="break-all">{u.unit_id}: {u.stage} · {u.product_id ?? 'product unset'} · {u.pack_id ?? 'unpacked'} · {u.custody.custody_id}<br />Current physical evidence: {u.state_event_id}{(u.batch_id || u.possession !== 'recorded' || u.custody.custody_id.startsWith('machine:')) && <span className="block text-amber-100">Unavailable: loaded membership does not identify which units remain held. Record an actual identified physical removal or return first. Do not invent movement evidence to bypass this limit.</span>}</p>)}</div>
      </>}
      {action === 'packed' && <>{field('packPrefix', 'Physical pack batch identity', 'One stable numbered pack ID will be recorded for each selected processed card; keep that roster with the physical packs.')}<p className="text-sm text-white/60">Each pack contains one selected card. Packing does not move its custody or set its price.</p></>}
      {action === 'reserved' && <>{check('cancelReservation', 'Clear the planned reservation')}{field('custody', 'Planned destination custody')}{locationField}<p className="text-sm text-white/60">This records the plan. Physical dispatch and loading are separate actions.</p></>}
      {action === 'price_set' && <>{field('price', 'Intended asking price (USD)', 'Blank clears the intended price. Asking price never changes acquisition cost or proves revenue.')}</>}
      {action === 'custody_moved' && <>{field('fromCustody', 'Recorded origin custody')}<Field label="Physical movement type"><select className={inputClass} value={draft.movement} onChange={e => change('movement', e.target.value)}><option value="">Choose actual movement</option><option value="dispatch">Dispatched into transit</option><option value="receipt">Received from transit</option><option value="transfer">Physical transfer</option></select></Field>{field('custody', 'Actual destination custody', 'Dispatch uses transit: with the actual staff/vehicle custody identity. Machine receipt uses Load machine batch.')}{locationField}</>}
      {action === 'batch_loaded' && <>{field('batch', 'New loading-batch ID')}{scopeFields}{field('fromCustody', 'Recorded origin custody')}{locationField}</>}
      {action === 'sale_observed' && <>{scopeFields}{field('salesFrom', 'Sales interval start (UTC)')}{field('salesUntil', 'Sales interval end, exclusive (UTC)')}{field('quantity', 'Observed sold quantity')}{field('revenue', 'Actual product revenue (USD)', 'Blank means unknown. This is completed sales evidence, not asking price or payment collection.')}<p className="text-sm text-amber-100">Sales observations do not select individual sold cards. Save counts and batch reconciliation to establish aggregate coverage.</p></>}
      {action === 'stock_counted' && <>{scopeFields}{field('quantity', 'Actual counted quantity')}{check('identified', 'This physical count identifies exactly the selected remaining units; otherwise retain aggregate identity uncertainty.')}</>}
      {(action === 'batch_removed' || action === 'physical_return_observed') && <>{field('batch', 'Original loading-batch ID')}{scopeFields}{action === 'physical_return_observed' && field('originalSale', 'Original sales observation ID')}{field('quantity', 'Physically moved quantity')}{check('identified', 'Actual physical evidence identifies exactly the selected units; otherwise retain aggregate identity uncertainty.')}{field('custody', 'Actual destination custody')}{locationField}<p className="text-sm text-amber-100">A physical return changes stock evidence only. Record any completed monetary refund separately.</p></>}
      {action === 'refund_observed' && <>{field('originalSale', 'Original sales observation ID')}{field('revenue', 'Completed refund amount (USD)')}{field('refundRef', 'Unique completed refund reference')}<p className="text-sm text-white/60">Refund evidence changes no physical stock and cannot exceed remaining documented original revenue.</p></>}
      {action === 'batch_reconciled' && <>{field('batch', 'Recorded loading-batch ID')}{field('opening', 'Opening count event ID')}{field('closing', 'Closing count event ID')}{field('salesIds', 'Sales observation IDs', 'One stored event ID per line. Use the event history below.', true)}{field('movementIds', 'Other load / removal / return event IDs', 'Include every overlapping physical movement; the original load is already bound to this batch.', true)}{check('scopeComplete', 'The supplied opening, closing, sales and movements completely cover this machine/product/door scope.')}{field('scopeEvidence', 'Completeness assertion evidence')}{check('salesAttributed', 'The cited sales have been explicitly attributed to this loading batch with evidence.')}{field('attributionEvidence', 'Sales attribution evidence')}<p className="text-sm text-amber-100">Nonzero prior stock, overlapping loads, missing costs and partial mixed-cost consumption can remain ambiguous despite an assertion. No FIFO or individual sale identity is inferred.</p></>}
      </div><div className="flex gap-3"><button type="button" className={buttonClass} onClick={() => send('preview')}>Preview causal impact</button><button type="submit" className={buttonClass + ' border-amber-300/60 text-amber-100'}>Save evidenced workflow step</button></div></>}
      </fieldset></form>
      {preview && <div className={panelClass}><h3 className="font-semibold">{preview.outcome === 'PREVIEW' ? 'Preview' : 'Accepted evidence'} · {workflowActionLabels[preview.event.event_kind]}</h3><p className="mt-2 text-sm">Effective {preview.event.effective_at} · {preview.impact?.backdated ? 'Historical entry preserves the later recorded causal history.' : 'Causal validation passed.'}</p>{preview.event.event_kind === 'cost_assigned' && <p className="mt-2 text-sm">{preview.event.data.allocation.units.length} unit costs · {preview.event.data.assignment.basis.replaceAll('_', ' ')} · {preview.event.data.allocation.units.every(u => u.cost_cents !== null) ? money(preview.event.data.allocation.units.reduce((sum, u) => sum + (u.cost_cents ?? 0), 0)) : 'Per-card cost unset'}</p>}<details className="mt-3"><summary className="cursor-pointer text-sm text-white/60">Review exact event evidence</summary><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap break-all text-xs text-white/60">{JSON.stringify(preview.event, null, 2)}</pre></details></div>}
      <div className={panelClass}><h3 className="font-semibold">Recorded evidence · {view.events_total} events in this view</h3><div className="mt-3 space-y-3">{view.events.map(e => <details key={e.source_event_id} className="rounded-lg border border-white/10 p-3 text-xs"><summary className="cursor-pointer">{workflowActionLabels[e.event_kind]} · {e.effective_at}<span className="mt-1 block break-all text-white/50">{e.source_event_id}</span></summary><p className="mt-2 break-words text-white/60">{e.evidence_ref} · recorded by {e.recorded_by} at {e.recorded_at}</p><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(e.data, null, 2)}</pre></details>)}</div><div className="mt-3 flex gap-3"><button type="button" className={buttonClass} disabled={busy || !!pending || view.event_offset === 0} onClick={() => { const q = new URLSearchParams(query); q.set('event_offset', String(Math.max(0, view.event_offset - 100))); navigate(q.toString()); }}>Newer evidence</button><button type="button" className={buttonClass} disabled={busy || !!pending || view.event_offset + view.events.length >= view.events_total} onClick={() => { const q = new URLSearchParams(query); q.set('event_offset', String(view.event_offset + 100)); navigate(q.toString()); }}>Older evidence</button></div></div>
    </>}
  </div>;
}
