import {
  AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
  AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
  type AiGraderLabelV1Snapshot,
} from "../lib/aiGraderLabelV1";

export type AiGraderLabelV1NfcFitTestCard = {
  slot: number;
  referenceLabel: string;
  sourceUrls: readonly string[];
  snapshot: AiGraderLabelV1Snapshot;
};

export const AI_GRADER_LABEL_V1_NFC_FIT_TEST_CARDS = [
  {
    slot: 1,
    referenceLabel: "1986-87 Fleer Basketball #57 Michael Jordan rookie",
    sourceUrls: ["https://www.psacard.com/cardfacts/basketball-cards/1986-fleer/michael-jordan-57/5003"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s01",
      certId: "TEST-S01",
      grade: 10,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s01",
      identity: {
        category: "sport",
        year: "1986-87",
        manufacturer: "Fleer",
        productSet: "Basketball",
        playerName: "Michael Jordan",
        insert: "Rookie",
        cardNumber: "57",
        sport: "Basketball",
      },
    },
  },
  {
    slot: 2,
    referenceLabel: "1996-97 Topps Chrome Basketball #138 Kobe Bryant rookie",
    sourceUrls: ["https://www.psacard.com/cardfacts/basketball-cards/1996-topps-chrome/kobe-bryant-138/5446"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s02",
      certId: "TEST-S02",
      grade: 9.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s02",
      identity: {
        category: "sport",
        year: "1996-97",
        manufacturer: "Topps",
        productSet: "Chrome Basketball",
        playerName: "Kobe Bryant",
        insert: "Rookie",
        cardNumber: "138",
        sport: "Basketball",
      },
    },
  },
  {
    slot: 3,
    referenceLabel: "1992-93 Topps Basketball #362 Shaquille O'Neal rookie",
    sourceUrls: ["https://www.psacard.com/priceguide/basketball-card-values/1992-topps/1738"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s03",
      certId: "TEST-S03",
      grade: 9,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s03",
      identity: {
        category: "sport",
        year: "1992-93",
        manufacturer: "Topps",
        productSet: "Basketball",
        playerName: "Shaquille O'Neal",
        insert: "Rookie",
        cardNumber: "362",
        sport: "Basketball",
      },
    },
  },
  {
    slot: 4,
    referenceLabel: "1933 Goudey Big League Gum #53 Babe Ruth (Yellow Ruth)",
    sourceUrls: ["https://www.psacard.com/cardfacts/baseball-cards/1933-goudey/babe-ruth-53/20283"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s04",
      certId: "TEST-S04",
      grade: 8.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s04",
      identity: {
        category: "sport",
        year: "1933",
        manufacturer: "Goudey",
        productSet: "Big League Gum",
        playerName: "Babe Ruth",
        parallel: "Yellow Ruth",
        cardNumber: "53",
        sport: "Baseball",
      },
    },
  },
  {
    slot: 5,
    referenceLabel: "2000 Playoff Contenders Football #144 Tom Brady autographed Rookie Ticket",
    sourceUrls: ["https://www.psacard.com/cardfacts/football-cards/2000-playoff-contenders/tom-brady-autographed-144/130232"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s05",
      certId: "TEST-S05",
      grade: 8,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s05",
      identity: {
        category: "sport",
        year: "2000",
        manufacturer: "Playoff",
        productSet: "Contenders Football",
        playerName: "Tom Brady",
        parallel: "Autographed",
        insert: "Rookie Ticket",
        cardNumber: "144",
        sport: "Football",
        autograph: true,
      },
    },
  },
  {
    slot: 6,
    referenceLabel: "1989 Score Football #257 Barry Sanders rookie",
    sourceUrls: ["https://www.psacard.com/cardfacts/football-cards/1989-score/barry-sanders-257/13033"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s06",
      certId: "TEST-S06",
      grade: 7.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s06",
      identity: {
        category: "sport",
        year: "1989",
        manufacturer: "Score",
        productSet: "Football",
        playerName: "Barry Sanders",
        insert: "Rookie",
        cardNumber: "257",
        sport: "Football",
      },
    },
  },
  {
    slot: 7,
    referenceLabel: "1979-80 O-Pee-Chee Hockey #18 Wayne Gretzky rookie",
    sourceUrls: ["https://www.psacard.com/cardfacts/hockey-cards/1979-o-pee-chee/wayne-gretzky-18/2583"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s07",
      certId: "TEST-S07",
      grade: 7,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s07",
      identity: {
        category: "sport",
        year: "1979-80",
        manufacturer: "O-Pee-Chee",
        productSet: "Hockey",
        playerName: "Wayne Gretzky",
        insert: "Rookie",
        cardNumber: "18",
        sport: "Hockey",
      },
    },
  },
  {
    slot: 8,
    referenceLabel: "2003-04 Topps Chrome Basketball #111 LeBron James rookie",
    sourceUrls: ["https://www.psacard.com/cardfacts/basketball-cards/2003-topps-chrome/lebron-james-111/112887"],
    snapshot: {
      templateId: AI_GRADER_SPORTS_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-s08",
      certId: "TEST-S08",
      grade: 6.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/s08",
      identity: {
        category: "sport",
        year: "2003-04",
        manufacturer: "Topps",
        productSet: "Chrome Basketball",
        playerName: "LeBron James",
        insert: "Rookie",
        cardNumber: "111",
        sport: "Basketball",
      },
    },
  },
  {
    slot: 9,
    referenceLabel: "1999 Pokemon Base Set Charizard #4/102 Holo Rare",
    sourceUrls: [
      "https://www.pokemon.com/uk/pokemon-news/favorite-pokemon-tcg-cards-from-the-kanto-era",
      "https://www.tcgplayer.com/categories/trading-and-collectible-card-games/pokemon/price-guides/base-set",
    ],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p01",
      certId: "TEST-P01",
      grade: 10,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p01",
      identity: {
        category: "tcg",
        year: "1999",
        game: "Pokemon",
        productSet: "Base Set",
        cardName: "Charizard",
        parallel: "Holo Rare",
        cardNumber: "4/102",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 10,
    referenceLabel: "1999 Pokemon Base Set Pikachu #58/102 Common (Yellow Cheeks)",
    sourceUrls: ["https://www.psacard.com/auctionprices/tcg-cards/1999-pokemon-game/pikachu/1705070"],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p02",
      certId: "TEST-P02",
      grade: 9.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p02",
      identity: {
        category: "tcg",
        year: "1999",
        game: "Pokemon",
        productSet: "Base Set",
        cardName: "Pikachu",
        parallel: "Common - Yellow Cheeks",
        cardNumber: "58/102",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 11,
    referenceLabel: "1999 Pokemon Base Set Blastoise #2/102 Holo Rare",
    sourceUrls: ["https://www.pokemon.com/uk/pokemon-news/favorite-pokemon-tcg-cards-from-the-kanto-era"],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p03",
      certId: "TEST-P03",
      grade: 9,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p03",
      identity: {
        category: "tcg",
        year: "1999",
        game: "Pokemon",
        productSet: "Base Set",
        cardName: "Blastoise",
        parallel: "Holo Rare",
        cardNumber: "2/102",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 12,
    referenceLabel: "1999 Pokemon Base Set Venusaur #15/102 Holo Rare",
    sourceUrls: ["https://www.psacard.com/auctionprices/tcg-cards/1999-pokemon-game/venusaur-holo/auction/-5194511980355655319"],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p04",
      certId: "TEST-P04",
      grade: 8.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p04",
      identity: {
        category: "tcg",
        year: "1999",
        game: "Pokemon",
        productSet: "Base Set",
        cardName: "Venusaur",
        parallel: "Holo Rare",
        cardNumber: "15/102",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 13,
    referenceLabel: "1999 Pokemon Base Set Mewtwo #10/102 Holo Rare",
    sourceUrls: ["https://www.psacard.com/cardfacts/non-sports-cards/1999-nintendo-pokemon-game/mewtwo-holo-10/605268"],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p05",
      certId: "TEST-P05",
      grade: 8,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p05",
      identity: {
        category: "tcg",
        year: "1999",
        game: "Pokemon",
        productSet: "Base Set",
        cardName: "Mewtwo",
        parallel: "Holo Rare",
        cardNumber: "10/102",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 14,
    referenceLabel: "1999 Pokemon Fossil Gengar #5/62 Holo Rare",
    sourceUrls: ["https://www.psacard.com/cardfacts/non-sports-cards/1999-nintendo-pokemon-fossil/gengar-holo-1st-edition-5/641226"],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p06",
      certId: "TEST-P06",
      grade: 7.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p06",
      identity: {
        category: "tcg",
        year: "1999",
        game: "Pokemon",
        productSet: "Fossil",
        cardName: "Gengar",
        parallel: "Holo Rare",
        cardNumber: "5/62",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 15,
    referenceLabel: "2000 Pokemon Neo Genesis Lugia #9/111 Holo Rare",
    sourceUrls: ["https://www.psacard.com/cardfacts/non-sports-cards/2000-nintendo-pokemon-neo-genesis/lugia-holo-9/845690"],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p07",
      certId: "TEST-P07",
      grade: 7,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p07",
      identity: {
        category: "tcg",
        year: "2000",
        game: "Pokemon",
        productSet: "Neo Genesis",
        cardName: "Lugia",
        parallel: "Holo Rare",
        cardNumber: "9/111",
        manufacturer: "Wizards of the Coast",
      },
    },
  },
  {
    slot: 16,
    referenceLabel: "2005 Pokemon EX Deoxys Rayquaza #107/107 Gold Star Holo Rare",
    sourceUrls: [
      "https://assets.pokemon.com/assets/cms/pdf/tcg/carddex/EX_Deoxys.pdf",
      "https://www.psacard.com/cardfacts/non-sports-cards/2005-nintendo-pokemon-ex-deoxys/rayquaza-holo-gold-star-107/753114",
    ],
    snapshot: {
      templateId: AI_GRADER_POKEMON_LABEL_V1_TEMPLATE_ID,
      reportId: "nfc-fit-test-p08",
      certId: "TEST-P08",
      grade: 6.5,
      publicReportUrl: "https://example.invalid/nfc-fit-test/p08",
      identity: {
        category: "tcg",
        year: "2005",
        game: "Pokemon",
        productSet: "EX Deoxys",
        cardName: "Rayquaza",
        parallel: "Gold Star - Holo Rare",
        cardNumber: "107/107",
        manufacturer: "Pokemon USA",
      },
    },
  },
] satisfies readonly AiGraderLabelV1NfcFitTestCard[];
