// Start the loopback synthetic preview before this separate browser check.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';
const output = process.env.ATLAS_BROWSER_EVIDENCE;
if (!output) throw new Error('ATLAS_BROWSER_EVIDENCE must name a task-owned output directory');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1200, height: 1100 } });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const wait = async predicate => { for (let i = 0; i < 60; i++) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 50)); } throw new Error('Browser condition timed out'); };
const confirm = page.getByRole('button', { name: 'Confirm both sides', exact: true });
const front = page.getByRole('region', { name: 'Front geometry' });
const state = () => page.evaluate(() => window.fixtureControl.state());
const reset = async () => { await page.evaluate(() => window.fixtureControl.reset()); await page.reload(); await wait(() => confirm.isEnabled()); };
try {
  await page.goto('http://127.0.0.1:4179/?autoPrepare=0');
  await wait(() => confirm.isEnabled());
  await page.screenshot({ path: `${output}/desktop.png`, fullPage: true });
  const original = await state();
  for (const fault of ['missing', 'hash', 'load', 'dimensions']) {
    await page.evaluate(fault => window.fixtureControl.imageFault(fault), fault);
    await wait(() => confirm.isDisabled());
    if (fault !== 'missing' && fault !== 'hash') await wait(async () => (await front.getByRole('alert').count()) > 0);
    await page.evaluate(() => window.fixtureControl.imageFault('none'));
    await wait(() => confirm.isEnabled());
  }
  checks.push('Missing, wrong-hash, failed and wrong-dimension images block confirmation; restored exact views recover.');
  await page.getByRole('button', { name: 'Printed border', exact: true }).click();
  const revision = (await state()).sides.FRONT.preparationRevision;
  await page.evaluate(() => window.fixtureControl.reprepareSameBytes('FRONT'));
  await wait(() => page.getByRole('button', { name: 'FRONT printed border Top left', exact: true }).isEnabled());
  assert.equal((await state()).sides.FRONT.preparationRevision, revision + 1);
  checks.push('Equal-byte prepared revision with the same URL reloads and restores editing readiness.');
  await reset();
  await page.getByRole('button', { name: 'Printed border', exact: true }).click();
  await page.getByRole('button', { name: 'FRONT printed border Top left', exact: true }).press('ArrowRight');
  assert.equal(await confirm.isEnabled(), false);
  assert.equal(await page.getByRole('button', { name: 'Physical edge', exact: true }).isEnabled(), false);
  await page.evaluate(() => window.fixtureControl.failSave());
  await front.getByRole('button', { name: 'Save outline', exact: true }).click();
  await wait(async () => (await front.getByRole('alert').innerText()).includes('retained'));
  assert.deepEqual(await state(), original);
  assert.equal(await front.getByRole('button', { name: 'Save outline', exact: true }).isEnabled(), true);
  await front.getByRole('button', { name: 'Save outline', exact: true }).click();
  await wait(() => confirm.isEnabled());
  const saved = await state();
  assert.equal(saved.sides.FRONT.printed.quad[0].x, original.sides.FRONT.printed.quad[0].x + 1/1270);
  assert.deepEqual(saved.sides.BACK, original.sides.BACK);
  assert.deepEqual(saved.sides.FRONT.prepared, original.sides.FRONT.prepared);
  await page.reload(); await wait(() => confirm.isEnabled());
  assert.deepEqual(await state(), saved);
  checks.push('One-pixel printed edit retains its draft on save failure, then persists/reloads; Back and prepared pixels stay identical.');
  await page.getByRole('button', { name: 'Printed border', exact: true }).click();
  await page.getByRole('button', { name: 'FRONT printed border Top left', exact: true }).press('Shift+ArrowDown');
  await page.evaluate(() => window.fixtureControl.externalEdit('FRONT'));
  await wait(async () => (await front.getByRole('alert').count()) > 0);
  assert.equal(await front.getByRole('button', { name: 'Save outline', exact: true }).isEnabled(), false);
  await front.getByRole('button', { name: 'Discard adjustment', exact: true }).click();
  await wait(() => confirm.isEnabled());
  checks.push('A newer same-side change retains but fences the unsaved draft until it is discarded.');
  await reset();
  await page.getByLabel('FRONT zoom', { exact: true }).selectOption('2');
  await page.getByRole('button', { name: 'FRONT pan left', exact: true }).click({ clickCount: 2 });
  await page.getByRole('button', { name: 'FRONT pan up', exact: true }).click({ clickCount: 2 });
  await front.getByRole('checkbox').uncheck();
  const handle = page.getByRole('button', { name: 'FRONT physical edge Top left', exact: true });
  const box = await handle.boundingBox();
  const plane = await front.locator('.am-image-plane').boundingBox();
  await page.mouse.move(box.x + box.width/2, box.y + box.height/2);
  await page.mouse.down(); await page.mouse.move(box.x + box.width/2 + 12, box.y + box.height/2 + 10, { steps: 4 }); await page.mouse.up();
  await front.getByRole('button', { name: 'Save outline', exact: true }).click();
  await wait(async () => (await state()).sides.FRONT.prepared === null);
  const moved = await state();
  assert.ok(Math.abs(moved.sides.FRONT.physical.quad[0].x - original.sides.FRONT.physical.quad[0].x - 12/plane.width) < .0001);
  assert.ok(Math.abs(moved.sides.FRONT.physical.quad[0].y - original.sides.FRONT.physical.quad[0].y - 10/plane.height) < .0001);
  assert.deepEqual(moved.sides.BACK, original.sides.BACK);
  assert.equal(await confirm.isEnabled(), false);
  assert.ok((await front.innerText()).includes('Needs preparation'));
  checks.push('Zoomed/panned pointer drag maps to source coordinates; physical save invalidates only Front preparation and blocks confirmation.');
  await reset(); await confirm.click();
  await wait(async () => Boolean((await state()).sides.FRONT.confirmation));
  assert.ok((await state()).sides.BACK.confirmation);
  assert.equal(await confirm.isEnabled(), false);
  checks.push('Both-side confirmation updates both current geometry reviews and disables duplicate confirmation.');
  await reset(); await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  const dimensions = await page.evaluate(() => ({ body: document.documentElement.scrollWidth, viewport: innerWidth, sides: [...document.querySelectorAll('.am-side')].map(n => ({ x: n.getBoundingClientRect().x, y: n.getBoundingClientRect().y, bottom: n.getBoundingClientRect().bottom })), image: document.querySelector('.am-image-plane').getBoundingClientRect().toJSON() }));
  assert.ok(dimensions.body <= dimensions.viewport);
  assert.ok(dimensions.sides[1].y >= dimensions.sides[0].bottom);
  assert.ok(Math.abs(dimensions.image.width/dimensions.image.height - 1200/1540) < .001);
  checks.push('390-pixel layout stacks Front then Back without horizontal overflow or image distortion.');
  await page.setViewportSize({ width: 1200, height: 1100 });
  await reset(); await page.goto('http://127.0.0.1:4179/?autoPrepare=1');
  await wait(() => confirm.isEnabled());
  const beforePreparation = await state();
  await page.getByRole('button', { name: 'FRONT physical edge Top left', exact: true }).press('ArrowRight');
  await front.getByRole('button', { name: 'Save outline', exact: true }).click();
  await wait(async () => (await state()).sides.FRONT.preparationRevision > beforePreparation.sides.FRONT.preparationRevision);
  const afterPreparation = await state();
  assert.deepEqual(afterPreparation.sides.BACK, beforePreparation.sides.BACK);
  assert.equal(afterPreparation.sides.FRONT.printed.actor, 'ENGINE');
  assert.notEqual(afterPreparation.sides.FRONT.prepared.frame.rectified.sha256, beforePreparation.sides.FRONT.prepared.frame.rectified.sha256);
  await page.getByRole('button', { name: 'Printed border', exact: true }).click();
  await wait(() => confirm.isEnabled());
  const actualUrl = await front.getByRole('img').getAttribute('src');
  assert.ok(actualUrl.endsWith('.webp'));
  await page.reload(); await wait(() => confirm.isEnabled());
  assert.deepEqual(await state(), afterPreparation);
  await page.getByRole('button', { name: 'Printed border', exact: true }).click();
  await wait(() => confirm.isEnabled());
  assert.equal(await front.getByRole('img').getAttribute('src'), actualUrl);
  checks.push('Physical save automatically runs real CPU preparation, adopts the current engine border, preserves Back and reloads the actual immutable derivative.');
  assert.deepEqual(errors, []);
  await writeFile(`${output}/browser-results.json`, JSON.stringify({ passed: true, checks, browser: await browser.version(), errors }, null, 2));
  process.stdout.write(JSON.stringify({ passed: checks.length, errors }) + '\n');
} finally { await browser.close(); }
