import test from 'node:test';
import assert from 'node:assert/strict';
import { customerCapacity, capacityBlockers, capacityWeek } from '../src/capacity.mjs';
const now = new Date('2026-10-01T23:00:00.000Z');
function shared(held=20,accepted=0) { return {version:'atlas-weekly-capacity-v2',scope:'SHARED',unit:'CARDS',timeZone:'America/Los_Angeles',resetLocalTime:'00:01',asOf:now.toISOString(),...capacityWeek(now),total:{state:'AVAILABLE',quotaCards:1000,heldCards:held,acceptedCards:accepted,remainingCards:1000-held-accepted},pools:[{channel:'MAIL_IN',heldCards:held,acceptedCards:0},{channel:'DEALER_DROP_OFF',heldCards:0,acceptedCards:accepted}]}; }
test('20 cards reserve against ONE1000-card total and leave980 through either route',()=>{const v=customerCapacity(shared());assert.equal(v.total.remainingCards,980);assert.deepEqual(capacityBlockers(v,'MAIL_IN',980),[]);assert.deepEqual(capacityBlockers(v,'KIOSK',981),['WEEKLY_CAPACITY_FULL']);assert.deepEqual(capacityBlockers(v,'DEALER_DROP_OFF',981),['WEEKLY_CAPACITY_FULL']);});
test('UNKNOWN hold and accepted card totals cannot be counted twice or forged per route',()=>{const v=shared(20,15);assert.equal(customerCapacity(v).total.remainingCards,965);for(const change of [v=>v.total.remainingCards=980,v=>v.pools[1].acceptedCards=14,v=>v.pools[1]=v.pools[0],v=>v.total.quotaCards=NaN]){const bad=structuredClone(v);change(bad);assert.throws(()=>customerCapacity(bad),{code:'INVALID_CAPACITY_SNAPSHOT'});}});
test('the shared contract strips customer/private fields and never carries route quota claims',()=>{const v=shared();v.paymentId='private';v.total.customer='private';v.pools[0].quotaCards=1000;const out=customerCapacity(v);assert(!JSON.stringify(out).includes('private'));assert.equal(out.pools[0].quotaCards,undefined);assert.throws(()=>capacityBlockers(out,'INVENTED_ROUTE',1),{code:'INVALID_CAPACITY_CHANNEL'});});
test('an unconfigured next week stays NULL with no recurring1000 default',()=>{const v=shared();v.asOf='2026-10-05T07:01:00.000Z';Object.assign(v,capacityWeek(new Date(v.asOf)));v.total={state:'NOT_CONFIGURED',quotaCards:null,heldCards:null,acceptedCards:null,remainingCards:null};v.pools.forEach(p=>{p.heldCards=null;p.acceptedCards=null;});assert.equal(customerCapacity(v).total.remainingCards,null);assert.deepEqual(capacityBlockers(v,'MAIL_IN',1),['WEEKLY_CAPACITY_NOT_CONFIGURED']);});
test('shared reset validates exact Monday00:01 including DST; wrong reset is rejected',()=>{for(const at of ['2026-03-06T20:00:00.000Z','2026-10-30T20:00:00.000Z']){const v=shared();v.asOf=at;Object.assign(v,capacityWeek(new Date(at)));assert.deepEqual(customerCapacity(v).weekStartsAt,capacityWeek(new Date(at)).weekStartsAt);}const bad=shared();bad.resetsAt='2026-10-05T00:01:00.000Z';assert.throws(()=>customerCapacity(bad),{code:'INVALID_CAPACITY_SNAPSHOT'});});
