const test = require('node:test');
const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const { createInventoryWorkflowAdminHandlerV2, createFinancialWorkflowReadHandlerV2 } = require('../dist/database/src/inventoryWorkflowV2Http');
const { CardInventoryErrorV2 } = require('../dist/database/src/cardInventoryV2');
const token = 'fixture-only-scoped-workflow-token-1234567890', tokenHash = createHash('sha256').update(token).digest('hex');
const response = () => ({ statusCode: 0, headers: {}, body: null, status(n) { this.statusCode = n; return this; }, setHeader(k, v) { this.headers[k] = v; }, json(v) { this.body = v; } });
const req = (overrides = {}) => ({ method: 'POST', headers: { authorization: 'Bearer fixture-human-session' }, query: {}, body: { mode: 'record', command: {} }, ...overrides });
test('workflow admin read/preview/write all reject read capability and static keys before auth/database', async () => { let calls = 0; const handler = createInventoryWorkflowAdminHandlerV2({ tokenHash: () => tokenHash, requireAdmin: async () => { calls++; }, read: async () => { calls++; }, record: async () => { calls++; } }); for (const method of ['GET', 'POST']) for (const headers of [{ authorization: 'Bearer ' + token }, { 'x-operator-key': 'fixture-operator' }]) { const r = response(); await handler(req({ method, headers }), r); assert.equal(r.statusCode, 403); assert.equal(r.headers['Cache-Control'], 'private, no-store'); } assert.equal(calls, 0); });
test('workflow actor comes only from human session and preview uses same writer dependency', async () => { const writes = []; const handler = createInventoryWorkflowAdminHandlerV2({ tokenHash: () => tokenHash, requireAdmin: async () => ({ user: { id: 'fixture-server-actor' }, authority: 'auth-service' }), read: async () => ({}), record: async (...args) => { writes.push(args); return { outcome: args[2] ? 'PREVIEW' : 'RECORDED' }; } }); for (const mode of ['preview', 'record']) { const r = response(); await handler(req({ body: { mode, command: { fixture: true } } }), r); assert.equal(r.statusCode, 200); } assert.deepEqual(writes, [[{ fixture: true }, 'fixture-server-actor', true], [{ fixture: true }, 'fixture-server-actor', false]]); });
test('unauthorized sessions and unavailable auth do not reveal error details or query source', async () => { let calls = 0; for (const statusCode of [401, 403, undefined]) { const handler = createInventoryWorkflowAdminHandlerV2({ tokenHash: () => tokenHash, requireAdmin: async () => { throw { statusCode, message: 'fixture:private-auth-detail' }; }, read: async () => calls++, record: async () => calls++ }); const r = response(); await handler(req(), r); assert.equal(r.statusCode, statusCode ?? 503); assert.doesNotMatch(JSON.stringify(r.body), /private-auth/); } assert.equal(calls, 0); });
test('query and payload shape are strict; source conflicts remain readable and infrastructure errors redacted', async () => { let calls = 0; const handler = createInventoryWorkflowAdminHandlerV2({ tokenHash: () => tokenHash, requireAdmin: async () => ({ user: { id: 'fixture-admin' } }), read: async () => { calls++; }, record: async input => { calls++; if (input.conflict) throw new CardInventoryErrorV2('CONFLICT', 'Quantity exceeds original observed sale'); throw new Error('postgresql://private:test@host'); } }); for (const options of [{ query: { extra: 'no' } }, { body: { mode: 'record', command: {}, actor: 'forged' } }, { method: 'GET', query: { lot_offset: '-1' } }]) { const r = response(); await handler(req(options), r); assert.equal(r.statusCode, 400); } assert.equal(calls, 0); const conflict = response(); await handler(req({ body: { mode: 'record', command: { conflict: true } } }), conflict); assert.equal(conflict.statusCode, 409); assert.match(conflict.body.message, /exceeds/); const unavailable = response(); await handler(req(), unavailable); assert.equal(unavailable.statusCode, 503); assert.doesNotMatch(JSON.stringify(unavailable.body), /private|postgresql/); });
test('workflow export has schema2 independent snapshot namespace and rejects cursor drift without reads', async () => { let calls = 0; const expected = { page: { schema_version: 2, source_system: 'ten-kings-card-platform-v2', snapshot_id: 'v2-inventory-workflow:0', after_sequence: 0, through_sequence: 0, events: [] }, snapshot_through_sequence: 0 }; const handler = createFinancialWorkflowReadHandlerV2({ tokenHash: () => tokenHash, readPage: async () => { calls++; return expected; } }); for (const query of [{ after_sequence: '-1' }, { after_sequence: '0', limit: '1001' }, { after_sequence: ['0', '1'] }, { after_sequence: '0', token }]) { const r = response(); await handler(req({ method: 'GET', headers: { authorization: 'Bearer ' + token }, query }), r); assert.equal(r.statusCode, 400); } assert.equal(calls, 0); const r = response(); await handler(req({ method: 'GET', headers: { authorization: 'Bearer ' + token }, query: { after_sequence: '0' } }), r); assert.equal(r.statusCode, 200); assert.deepEqual(r.body, expected); });
test('receipt cancellation uses the same human writer for preview/save and never accepts extra deletion authority', async () => {
  const { parseWorkflowCommandV2 } = require('../dist/database/src/inventoryWorkflowV2'); const calls = [];
  const handler = createInventoryWorkflowAdminHandlerV2({ tokenHash: () => tokenHash, requireAdmin: async () => ({ user: { id: 'fixture-human-admin' } }), read: async () => ({}), record: async (input, actor, preview) => { const command = parseWorkflowCommandV2(input); calls.push({ command, actor, preview }); return { outcome: preview ? 'PREVIEW' : 'RECORDED' }; } });
  const command = { request_id: 'fixture-cancellation-request', event_kind: 'purchase_cancelled', effective_at: '2026-01-02T00:00:00.000Z', evidence_ref: 'fixture:entry-correction', data: { lot_id: 'fixture-lot', purchase_event_id: 'fixture-receipt', reason: 'Wrong quantity was entered' } };
  for (const mode of ['preview', 'record']) { const r = response(); await handler(req({ body: { mode, command } }), r); assert.equal(r.statusCode, 200); }
  assert.deepEqual(calls, [{ command, actor: 'fixture-human-admin', preview: true }, { command, actor: 'fixture-human-admin', preview: false }]);
  const bad = response(); await handler(req({ body: { mode: 'record', command: { ...command, data: { ...command.data, delete_receipt: true } } } }), bad); assert.equal(bad.statusCode, 400); assert.equal(calls.length, 2);
});
