import test from 'node:test';
import assert from 'node:assert/strict';
import {publicationFixture} from '../../../packages/atlas-connected-manual/test/publication-fixture.mjs';
import {createApprovedFilmManifest,parseApprovedFilmManifest,filmSelector,approvedFilmFilename} from '@atlas/report-view/approved-film-contract';
import {approvedFilmHandler} from '../lib/server/film-http.mjs';
import {createFilmScene,sampleFilm,projectFilmPoint,regionBounds} from '../../../packages/atlas-manual-workspace/src/approved-report-tour.mjs';
import {filmRecordingFormat,boundedFilmResponse,loadApprovedFilmManifest} from '../../../packages/atlas-manual-workspace/src/approved-film-export.mjs';
import {normalizeFilmDedication} from '../../../packages/atlas-manual-workspace/src/approved-film-renderer.mjs';
async function fixture(){const f=await publicationFixture();await f.publication.publish({},f.cardId,f.actionId);const manifest=JSON.parse(f.row.manifest);const packet=await f.artifacts.read(manifest.packet.ref,{cardId:f.cardId,kind:'PUBLIC_REPORT',sourceHash:manifest.packet.sourceHash});return{packet,publicHash:f.row.public_hash};}
test('optional film dedication preserves ordinary names, digits and Unicode without control characters',()=>{
  for(const name of ['Samuel Duff 12','Francis Ford 007','Zoë François','李明 😀'])assert.equal(normalizeFilmDedication(name),name);
  assert.equal(normalizeFilmDedication('  Ma\u0000r\nk\u007f\u0085  '),'Mark');
  assert.equal(normalizeFilmDedication(null),'');
  const long='😀'.repeat(33);assert.equal(normalizeFilmDedication(long),'😀'.repeat(32));
  assert.equal(normalizeFilmDedication('a'.repeat(31)+'😀x'),'a'.repeat(31)+'😀');
});
function response(){return{statusCode:0,headers:{},body:null,setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},end(){return this;},json(v){this.body=v;return this;}};}
test('film pins existing approved packet, awarded half grade and exact original media',async()=>{const f=await fixture(),before=JSON.stringify(f),m=createApprovedFilmManifest(f);assert.deepEqual(m.packet,f.packet);assert.equal(JSON.stringify(f),before);assert.equal(m.packet.report.finalGrade,Math.round(m.packet.report.grade.overall.rawGrade*2)/2);assert.equal(m.templateVersion,'atlas-evidence-cinematic-v1');assert.deepEqual(parseApprovedFilmManifest(m,m.reportUrl),m);assert.throws(()=>parseApprovedFilmManifest({...m,reportUrl:m.reportUrl+'0'}));assert.throws(()=>parseApprovedFilmManifest({...m,duration:20}));assert.equal(approvedFilmFilename(m,'mp4'),`${m.packet.reportNumber}-v1.mp4`);});
test('unversioned, foreign, encoded and duplicated selectors cannot open export',()=>{for(const value of['/reports/ar_'+'a'.repeat(24),'https://atlasgrading.com/reports/ar_'+'a'.repeat(24)+'?v=1','/reports/ar_'+'a'.repeat(24)+'?v=1&v=2','/reports/ar_'+'a'.repeat(24)+'?v=2147483648',null])assert.equal(filmSelector(value),null);assert.equal(filmSelector('/reports/ar_'+'a'.repeat(24)+'?v=1').version,1);});
test('film HTTP delegates only to current approved reader and returns no retired sample',async()=>{const f=await fixture();let calls=0;const handler=approvedFilmHandler(()=>({read:async()=>{calls++;return f;}}));const query={token:f.packet.publicToken,v:'1'};const ok=response();await handler({method:'GET',query},ok);assert.equal(ok.statusCode,200);assert.equal(ok.body.publicHash,f.publicHash);assert.match(ok.headers['Cache-Control'],/no-store/);for(const req of[{method:'POST',query},{method:'GET',query:{...query,v:undefined}},{method:'GET',query:{...query,source:'private'}}]){const res=response();await handler(req,res);assert.ok([404,405].includes(res.statusCode));}assert.equal(calls,1);const retired=response();await approvedFilmHandler(()=>({read:async()=>null}))({method:'GET',query},retired);assert.equal(retired.statusCode,404);assert.equal(retired.body,null);const fail=response();await approvedFilmHandler(()=>({read:async()=>{throw Error('private');}}))({method:'GET',query},fail);assert.equal(fail.statusCode,503);assert.equal(fail.body,null);});
test('saved region cell edges keep mixed measurements separate and projection continuous',async()=>{const m=createApprovedFilmManifest(await fixture()),scene=createFilmScene(m);assert.equal(scene.sides.FRONT.findings.length+scene.sides.BACK.findings.length,m.packet.report.findings.length);const region={canonicalContour:[{x:10/1269,y:20/1777},{x:28/1269,y:20/1777},{x:28/1269,y:27/1777},{x:10/1269,y:27/1777}]};assert.deepEqual(regionBounds(region),{x:10,y:20,width:19,height:8});const a=projectFilmPoint([.5,.5],'FRONT',sampleFilm(scene,4),720,1280),b=projectFilmPoint([.5,.5],'FRONT',sampleFilm(scene,4.001),720,1280);assert.ok(Math.hypot(a.x-b.x,a.y-b.y)<1);for(const t of[0,3,4.2,5,8.7,12,16])for(const side of['FRONT','BACK']){const p=projectFilmPoint([0,0],side,sampleFilm(scene,t),720,1280);assert.ok([p.x,p.y,p.depth].every(Number.isFinite));assert.ok(p.depth>0);}});
test('export reports actual supported container and rejects oversized bytes',async()=>{assert.equal(filmRecordingFormat(null),null);assert.deepEqual(filmRecordingFormat({isTypeSupported:t=>t==='video/webm;codecs=vp8'}),{mimeType:'video/webm;codecs=vp8',extension:'webm'});assert.equal(filmRecordingFormat({isTypeSupported:()=>true}).extension,'mp4');await assert.rejects(boundedFilmResponse(new Response(new Uint8Array(9)),8),/TOO_LARGE/);assert.equal((await boundedFilmResponse(new Response(new Uint8Array(8)),8)).length,8);});

test('client verifies public packet digest, exact version and cancellation before loading',async()=>{
  const m=createApprovedFilmManifest(await fixture());let requested;
  const fetcher=async(url,options)=>{requested={url,options};return new Response(JSON.stringify(m),{headers:{'content-type':'application/json'}});};
  assert.deepEqual(await loadApprovedFilmManifest(m.reportUrl,{fetcher}),m);
  assert.equal(requested.url,filmSelector(m.reportUrl).url);assert.equal(requested.options.credentials,'omit');assert.equal(requested.options.cache,'no-store');assert.equal(requested.options.redirect,'error');
  await assert.rejects(loadApprovedFilmManifest(m.reportUrl,{fetcher:async()=>new Response(JSON.stringify({...m,publicHash:'0'.repeat(64)}),{headers:{'content-type':'application/json'}})}),/BINDING_INVALID/);
  const controller=new AbortController();controller.abort();let called=false;
  await assert.rejects(loadApprovedFilmManifest(m.reportUrl,{signal:controller.signal,fetcher:async()=>{called=true;}}),{name:'AbortError'});assert.equal(called,false);
});
