export type VaultMode = "PRODUCTION" | "CERTIFICATION";
export type VaultRole = "RESTOCKER" | "TECHNICIAN" | "ADMIN";
export type VaultDoorState = "EMPTY" | "AVAILABLE" | "RESERVED" | "COMMITTED_SOLD" | "SERVICE_HOLD" | "DISABLED" | "EXCEPTION";
export type VaultPaymentState = "NOT_REQUESTED" | "REQUESTED" | "AUTHORIZED" | "DECLINED" | "CANCELLED" | "UNKNOWN" | "VEND_RESULT_PENDING" | "SETTLEMENT_PENDING" | "SETTLED" | "RECONCILIATION_REQUIRED";
export type VaultCommandState = "NOT_COMMITTED" | "COMMAND_INTENT_RECORDED" | "ACCEPTED" | "SENT_UNKNOWN" | "REJECTED" | "TIMEOUT" | "OUTPUT_RELEASED";
export type VaultSaleState = "CART_ACTIVE" | "CHECKOUT_REVALIDATING" | "RESERVED" | "PAYMENT_REQUESTED" | "PAYMENT_AUTHORIZED" | "FULFILLMENT_COMMITTED" | "OPEN_COMMAND_PENDING" | "OPEN_COMMAND_TERMINAL" | "VEND_RESULT_PENDING" | "SETTLEMENT_PENDING" | "SETTLED" | "COMPLETED" | "PAYMENT_DECLINED" | "PAYMENT_CANCELLED" | "PAYMENT_UNKNOWN" | "RECONCILIATION_REQUIRED" | "SUPPORT_REQUIRED";
export type VaultRestockItemState = "UNREVIEWED" | "FILLED" | "LEFT_EMPTY" | "EXCEPTION";
export type VaultHealthState = "READY" | "DEGRADED_CLOUD" | "DEGRADED_SYNC" | "BLOCKED_CONFIG" | "BLOCKED_TAX" | "BLOCKED_NAYAX" | "BLOCKED_CONTROLLER" | "BLOCKED_STORAGE" | "BLOCKED_CLOCK" | "SERVICE_LOCKED" | "RECOVERY_REQUIRED";
export type VaultPermission = "RESTOCK_RUN" | "SERVICE_LOCK" | "DIAGNOSTICS_VIEW" | "DOOR_TEST" | "SOFTWARE_RECOVERY" | "CERTIFICATION_COLLECT" | "CERTIFICATION_APPROVE" | "PRODUCT_MANAGE" | "TAX_MANAGE" | "SUPPORT_CONFIG_MANAGE" | "DOOR_PLAN_MANAGE" | "STAFF_MANAGE" | "FINANCIAL_RESOLVE" | "ENROLLMENT_MANAGE" | "CONFIG_PUBLISH";

export const VAULT_ALLOWED_PRICE_CENTS = [2500, 5000, 10000, 25000] as const;

const ALL_PERMISSIONS: readonly VaultPermission[] = ["RESTOCK_RUN", "SERVICE_LOCK", "DIAGNOSTICS_VIEW", "DOOR_TEST", "SOFTWARE_RECOVERY", "CERTIFICATION_COLLECT", "CERTIFICATION_APPROVE", "PRODUCT_MANAGE", "TAX_MANAGE", "SUPPORT_CONFIG_MANAGE", "DOOR_PLAN_MANAGE", "STAFF_MANAGE", "FINANCIAL_RESOLVE", "ENROLLMENT_MANAGE", "CONFIG_PUBLISH"];
const ROLE_PERMISSIONS: Record<VaultRole, ReadonlySet<VaultPermission>> = {
  RESTOCKER: new Set(["RESTOCK_RUN"]),
  TECHNICIAN: new Set(["RESTOCK_RUN", "SERVICE_LOCK", "DIAGNOSTICS_VIEW", "DOOR_TEST", "SOFTWARE_RECOVERY", "CERTIFICATION_COLLECT", "CERTIFICATION_APPROVE"]),
  ADMIN: new Set(ALL_PERMISSIONS),
};

export function roleMay(role: VaultRole, permission: VaultPermission): boolean {
  return ROLE_PERMISSIONS[role].has(permission);
}
