name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: corepack enable
      - run: pnpm install
      - run: pnpm --filter @tenkings/* run --if-present build

  docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: quality
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: wallet-service
            dockerfile: backend/wallet-service/Dockerfile
          - name: vault-service
            dockerfile: backend/vault-service/Dockerfile
          - name: marketplace-service
            dockerfile: backend/marketplace-service/Dockerfile
          - name: pricing-service
            dockerfile: backend/pricing-service/Dockerfile
          - name: pack-service
            dockerfile: backend/pack-service/Dockerfile
          - name: ingestion-service
            dockerfile: backend/ingestion-service/Dockerfile
          - name: vending-gw
            dockerfile: backend/vending-gw/Dockerfile
          - name: frontend
            dockerfile: frontend/nextjs-app/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' }}
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.sha }}
